/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    marginVertical: 10,
    width: '80%',
    fontSize: 16,
  },
  buttonContainer: {
    width: '80%',
    marginVertical: 10,
    backgroundColor: '#2596be',
    borderRadius: 5,
    borderColor: '#2596be',
    borderWidth: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
  },
  buttonContainerSecondary: {
    width: '80%',
    marginVertical: 10,
    backgroundColor: '#fff',
    borderRadius: 5,
    borderColor: '#2596be',
    borderWidth: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  buttonTextSecondary: {
    color: '#2596be',
    fontSize: 16,
  },
  horizontalLine: {
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    width: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  radioButtonsContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    marginRight: 10,
  },
  timeCard: {
    display: 'flex',
    flexDirection: 'row',
    borderRadius: 5,
    padding: 10,
    marginVertical: 10,
    width: '80%',
    justifyContent: 'space-between',
    backgroundColor: '#2596be',
    shadowColor: '#000',
    shadowOffset: {
      width: 10,
      height: 10,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3.84,
    elevation: 10,
    borderColor: '#fff',
    borderWidth: 2,
  },
  timeModifier: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  scheduleContainer: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
  },
  iconsContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '70%',
    justifyContent: 'flex-end',
  },
  icon: {
    marginHorizontal: 10,
  },
  roundedPlusBottomButton: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    position: 'absolute',
    bottom: 20,
  },
  timeText: {
    color: '#fff',
    fontSize: 36,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: -5,
  },
  dateTimePickerColor: {
    color: '#2596be',
    backgroundColor: '#2596be',
  },
  ScrollView: {
    flex: 1,
    width: '100%',
    display: 'flex',
    backgroundColor: 'transparent',
    paddingBottom: 20,
  },
});

export default styles;
